module.exports.authority = require('./authority')
module.exports.bodyParts = require('./bodyParts')
module.exports.pickup = require('./pickup')
module.exports.ridiculous = require('./ridiculous')
module.exports.nthBase = require('./nthBase')